### ISSUE TITLE
App

### ISSUE THREAD

**Issue by Donothir** [DevNulPavel/osx_battery_charge_limit#2]
Can you put this in a downloadable app? Because I don't use x-code and my space is small in my MBA 2011.

**Comment by DevNulPavel** [comment]
@Donothir 
Hi

You can use alternatives with GUI, they packed in standalone app: [charge-limiter](https://github.com/godly-devotion/charge-limiter) and [BatteryStatusShow](https://github.com/sicreative/BatteryStatusShow)

XCode is not required for using this script, only command-line tools required. You can install it with
`xcode-select --install` or download from https://developer.apple.com/download/more/

**Comment by Donothir** [comment]
THX! I didn't knew.

You could put this on your presentation page in a more usefriendly way. Us, non-programmers, are sometimes a little bit dumb regarding command-line usage...

If it was more "step-by-step", I'm pretty sure some people would be thankful.

Edit: Pyton3 instructions...

How to install Python3 is missing, I didn't had brew, so it was hard to install it. I had to use this command to install Homebrew:
*****
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
*****

Sould be included with your instructions, something like:
*****
If you don't have any experience in command line usage, you must use Python and the command line tools. Using terminal, put the following commands to install all necessary files:
Python (you must install Homebrew first, then you can install Python v.3)
1. sudo ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
2. sudo brew install python3

Command-line Tools (from Apple Xcode)
3. xcode-select --install

Once it's done, you can run the script in terminal from the directory in which main.py is located. See readme for details.
*****

**Comment by DevNulPavel** [comment]
@Donothir 
Ok, i'll add some additional instructions into README
