### ISSUE TITLE
No BCLM entry on MBP 13 2020, Big Sur 11.2.2?

### ISSUE THREAD

**Issue by cjmaria** [DevNulPavel/osx_battery_charge_limit#6]
Hello, 

Thank you for your work on this tool, it is exactly what I am looking for.
However, I tried to run your script with `sudo python3 main.py -s 65` but errors are produced.
```
ERROR: SMC out parse failed
valid "  BCLM  [ui8 ]  60 (bytes 3c)"
current "  BCLM  [    ]  no data"
```
I am using a 13-inch MBP, 2020 with M1 chip and Big Sur 11.2.2 and python 3.8.6.
The repo is cloned to `~/osx_battery_charge_limit` and the commands were ran from that directory.

`sudo ./smc-command_from_fan_control/smc -l | grep "BCLM"` returns no output was well, my complete output of smc -l is here: [https://pastebin.com/ehGgH95J](https://pastebin.com/ehGgH95J)
Am I using the script wrong? Has the BCLM key been removed?

**Comment by tmalloy** [comment]
I'm having the same issue.

**Comment by cjmaria** [comment]
It appears that the developer is already aware of this issue. There is extensive discussion on this issue here: [https://github.com/davidwernhart/AlDente/issues/52](https://github.com/davidwernhart/AlDente/issues/52) with a solution being identified here: [https://github.com/davidwernhart/AlDente/issues/52#issuecomment-777627075](https://github.com/davidwernhart/AlDente/issues/52#issuecomment-777627075)
