### ISSUE TITLE
Apple M1 support

### ISSUE THREAD

**Issue by lukasc-ubc** [DevNulPavel/osx_battery_charge_limit#7]
Any chance your tool may work (now or in the future) for the new M1 MacBook Air?
thank you
Lukas

**Comment by DevNulPavel** [comment]
@lukasc-ubc 
Unfortunately, new M1 devices do not have BCLM value in SMC params list. It requires special daemon for disabling battery charge in runtime.
I would recommend you [AlDenete](https://github.com/davidwernhart/AlDente), this tool contains M1 support.
